### ISSUE TITLE
No collapsing building?

### ISSUE THREAD

**Issue by sheepo99** [ninjamuffin99/canabalt-hf#9]
Not sure if it's just me, but the original classic flash Canabalt had occasional buildings that collapsed when you jumped on them. Why are they absent from this version?

**Comment by sheepo99** [comment]
Collapsing buildings were pretty common in the OG even at relatively lower speeds. I would recommend doing a side-by-side comparison!

Thank you for the reply!

**Comment by sheepo99** [comment]
Nevermind, I just did a comparison myself, and it seems you are right. One thing I recall is that when i played the game back in the day, I was mostly using a legacy machine that could cause some slowdowns; maybe that was affecting how the game interpreting speed, or maybe the game has had multiple versions that changed the setting overtime.

Still for the sake of confirmation, it's always good to double check :)

**Comment by ninjamuffin99** [comment]
haha, yeah if your machine is running it at slower framerate, it might seem like you're moving slower than you actually are!

this version runs it's logic a bit "unlocked", so 1 second of gameplay at 10fps vs 120fps, it will make the physics / math equivalent so that you'd end up in generally the same place after that 1 second. So definitely wanna make sure that various framerates run the game in the same way/manner. That's one of the new "features" of this version, so it definitely should be kept an eye on for any discrepancies that may come from that!

**Comment by ninjamuffin99** [comment]
I will close this issue for now, however if you end up poking through the code and noticing anything that makes collapsible buildings not occur as frequent as they should, feel free to ping here and I'll re-open and investigate !
